---
- name: "keyboard Shortcuts - System settings"
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/control-center"
    value: "'<Super>t'"
    state: present

- name: "keyboard Shortcuts - Default Browser"
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/www"
    value: "'<Super>w'"
    state: present

- name: "keyboard Shortcuts - Home"
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/home"
    value: "'<Super>e'"
    state: present

- name: "keyboard Shortcuts - Calculator"
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/calculator"
    value: "'<Super>c'"
    state: present

- name: "keyboard Shortcuts - Defining custom bindings"
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
    value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"
    state: present

- name: "keyboard Shortcuts - Terminator name"
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name"
    value: "'Launch Terminator'"
    state: present

- name: "keyboard Shortcuts - Terminator binding"
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding"
    value: "'<Primary><Alt>t'"
    state: present

- name: "keyboard Shortcuts - Terminator comand"
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command"
    value: "'/usr/bin/terminator'"
    state: present
