---
- name: Configure favourite apps in Gnome
  dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "['firefox.desktop', 'google-chrome.desktop', 'spotify.desktop', 'atom.desktop', 'jetbrains-idea.desktop', 'emacs.desktop', 'terminator.desktop', 'pamac-manager.desktop']"
    state: present

- include: top-bar.yml
- include: peripherals.yml
- include: keyboard-shortcuts.yml
- include: screensaver.yml
- include: dash-to-dock.yml
