---
- name: Install Utils
  pacman:
    name: '{{ utils }}'
    state: present
  become: yes

- name: Install Utils from Arch User Repository
  script: ../../../aur/install-aur.sh {{ item }}
  with_items: '{{ utils_aur }}'
  register: install_result
  changed_when: install_result.rc == 0
  failed_when: install_result.rc != 0 and install_result.rc != 255
  tags:
    - aur

- include: pip.yml

- name: Install Oh My Zsh
  script: ../files/install-oh-my-zsh.sh {{ user_name }}
  register: install_result
  changed_when: install_result.rc == 0
  failed_when: install_result.rc != 0 and install_result.rc != 255

- name: Configure Terminator
  copy:
    src: ../files/terminator_config
    dest: /home/{{ user_name }}/.config/terminator/config
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: 0644

- name: Create bash shell aliases
  lineinfile: dest=/home/{{ user_name }}/.bashrc regexp='{{ item }}' insertafter='alias more=less' line='{{ item }}' state=present
  with_items: "{{ shell_aliases }}"

- name: Create zsh shell aliases
  lineinfile: dest=/home/{{ user_name }}/.zshrc regexp='{{ item }}' insertafter='EOF' line='{{ item }}' state=present
  with_items: "{{ shell_aliases }}"

- name: Add zsh plugins
  lineinfile: dest=/home/{{ user_name }}/.zshrc regexp='{{ item }}' insertafter='plugins=' line='  {{ item }}' state=present
  with_items: "{{ zsh_plugins }}"

- name: Change zsh shell theme from 'robbyrussell' to 'agnoster'
  replace:
    path: /home/{{ user_name }}/.zshrc
    regexp: 'ZSH_THEME="robbyrussell"'
    replace: 'ZSH_THEME="agnoster"'
    backup: yes
