---
- name: Full system upgrade
  shell: yes Y | /usr/bin/pacman -Syu
  become: yes

- name: Clean pacman cache
  shell: yes Y | /usr/bin/pacman -Scc
  become: yes

- name: Install Utils
  pacman:
    name: '{{ utils }}'
    state: present
  become: yes

- name: Install Utils from Arch User Repository
  script: ../../../aur/install-aur.sh {{ item }}
  with_items: '{{ utils_aur }}'
  register: install_result
  changed_when: install_result.rc == 0
  failed_when: install_result.rc != 0 and install_result.rc != 255
  tags:
    - aur

- include: zsh.yml
- include: bash.yml

- name: Creates Workspace directory
  file:
    path: /home/{{ user_name }}/Workspace
    state: directory
  become_user: '{{ user_name }}'
  become: yes

- name: Add wheel to sudoers.d
  copy:
    dest: '/etc/sudoers.d/10-installer'
    content: |
      %wheel ALL=(ALL) ALL
    owner: root
    group: root
    mode: '0440'
  become: yes

- name: Comment out include dir in sudoers
  replace:
    path: /etc/sudoers
    regexp: '^#includedir /etc/sudoers\.d'
    replace: 'includedir /etc/sudoers.d'
    after: '## (the \'#\' here does not indicate a comment)'
    backup: yes
  become: yes

- name: Comment wheel group in sudoers
  replace:
    path: /etc/sudoers
    regexp: '^ %wheel ALL=\(ALL\) ALL'
    replace: '# %wheel ALL=(ALL) ALL'
    after: '## Uncomment to allow members of group wheel to execute any command'
    backup: yes
  become: yes

- name: Add the user to wheel group
  user:
    name: "{{ user_name }}"
    groups: wheel
    append: yes
  become: yes

