---
- name: Full system upgrade
  shell: yes Y | /usr/bin/pacman -Syu
  become: yes

- name: Clean pacman cache
  shell: yes Y | /usr/bin/pacman -Scc
  become: yes

- name: Install Utils
  pacman:
    name: '{{ utils }}'
    state: present
  become: yes

- name: Install Utils from Arch User Repository
  script: ../../../aur/install-aur.sh {{ item }}
  with_items: '{{ utils_aur }}'
  register: install_result
  changed_when: install_result.rc == 0
  failed_when: install_result.rc != 0 and install_result.rc != 255
  tags:
    - aur

- include: zsh.yml
- include: bash.yml

- name: Creates Workspace directory
  file:
    path: /home/{{ user_name }}/Workspace
    state: directory
  become_user: '{{ user_name }}'
  become: yes
