---
- name: Install Developer Tools
  pacman: name={{ item }} state=present
  with_items: '{{ developer_stack }}'
  become: yes

- name: Install Developer Tools from Arch User Repository
  script: ../../../aur/install-aur.sh {{ item }}
  with_items: '{{ developer_stack_aur }}'
  register: install_result
  changed_when: install_result.rc == 0
  failed_when: install_result.rc != 0 and install_result.rc != 255
  tags:
    - aur

- name: Enable and start the docker daemon
  systemd:
    name: docker
    enabled: yes
    state: started
    masked: no
  become: yes
