---
- name: Creating smb.conf with respected resources
  template:
    src: smb_conf.j2
    dest: /etc/samba/smb.conf
  become: yes
  tags:
    - services
    - samba

- name: Creating krb5.conf with respected resources
  template:
    src: krb5_conf.j2
    dest: /etc/krb5.conf
  become: yes
  tags:
    - services
    - samba

- name: Creating pam_winbind.conf with respected resources
  template:
    src: pam_winbind_conf.j2
    dest: /etc/security/pam_winbind.conf
  become: yes
  tags:
    - services
    - samba

- name: Make sure the Samba service is running
  systemd: state=started name=samba enabled=yes
  become: yes
  tags:
    - services
    - samba
